language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - rbx-head
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: rbx-head
    - rvm: ree
    - rvm: 1.8.7
    - rvm: ruby-head
notifications:
  email:
    - dendoh@gmail.com
